export const TaskFormMok = {
  id: '1',
  title: 'Prueba de titulo',
  completed: false,
  userId: 1,
  description: 'Prueba de descripcion',
};

export const TasksMock = [
  {
    id: '1',
    title: 'Prueba de titulo',
    completed: false,
    userId: 1,
    description: 'Prueba de descripcion',
  },
  {
    id: '2',
    title: 'Prueba de titulo',
    completed: false,
    userId: 2,
    description: 'Prueba de descripcion',
  },
  {
    id: '3',
    title: 'Prueba de titulo',
    completed: false,
    userId: 3,
    description: 'Prueba de descripcion',
  },
  {
    id: '4',
    title: 'Prueba de titulo',
    completed: false,
    userId: 4,
    description: 'Prueba de descripcion',
  },
  {
    id: '5',
    title: 'Prueba de titulo',
    completed: false,
    userId: 5,
    description: 'Prueba de descripcion',
  },
  {
    id: '6',
    title: 'Prueba de titulo',
    completed: false,
    userId: 6,
    description: 'Prueba de descripcion',
  },
  {
    id: '7',
    title: 'Prueba de titulo',
    completed: false,
    userId: 7,
    description: 'Prueba de descripcion',
  },
  {
    id: '8',
    title: 'Prueba de titulo',
    completed: false,
    userId: 8,
    description: 'Prueba de descripcion',
  },
  {
    id: '9',
    title: 'Prueba de titulo',
    completed: false,
    userId: 9,
    description: 'Prueba de descripcion',
  },
  {
    id: '10',
    title: 'Prueba de titulo',
    completed: false,
    userId: 10,
    description: 'Prueba de descripcion',
  },
];
